version: '3'

services:
  broker:
    image: signetframework/signet-broker:latest
    container_name: signet-broker
    deploy:
      restart_policy:
        condition: on-failure
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - PORT=3001
      - NODE_ENV=production
      - RDS_USERNAME=postgres
      - RDS_HOSTNAME=db
      - RDS_DB_NAME=postgres
      - RDS_PASSWORD=browni3s
    ports:
      - "3001:3001"
    networks:
      - app-network
    working_dir: /home/node/app
    command: ./wait-for.sh db:5432 -t 500 -- npm start
  db:
    image: signetframework/signet-db:latest
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
    container_name: db
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
