version: '3'

services:
  broker:
    image: newnewms/signet-broker
    container_name: signet-broker
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env
    environment:
      - PORT=3001
      - NODE_ENV=development
      - DEV_DB_USER=postgres
      - DEV_DB_HOST=db
      - DEV_DB_NAME=postgres
    ports:
      - "3003:3001"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: npm start
    # command: /home/node/app/node_modules/.bin/nodemon src/app.js
  db:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    restart: always
    container_name: db
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=$DEV_DB_PASSWORD
      - POSTGRES_DB=$DEV_DB_NAME
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
  node_modules:
