name: Server Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Test:
    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: 'server'

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_broker

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/


    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - run: npm ci
        working-directory: server

      - name: migrate db
        run: NODE_ENV=test npx knex migrate:latest && NODE_ENV=test npx knex seed:run
        working-directory: server/src/db
        env:
          TEST_DB_USER: postgres
          TEST_DB_PASSWORD: postgres
          TEST_DB_HOST: localhost
          TEST_DB_PORT: 5432
          PGPASSWORD: postgres

      - run: npm test
        working-directory: server
        env:
          TEST_DB_USER: postgres
          TEST_DB_PASSWORD: postgres
          TEST_DB_HOST: localhost
          TEST_DB_PORT: 5432
          PORT: 3001
          NODE_ENV: test
          PGPASSWORD: postgres
